id: I4753718D
legacy_id: P006847
ocr_import_info:
  bdrc_scan_id: W22250
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T00:03:00'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T21:04:55.290903+00:00'
last_modified: 2022-09-02 05:07:22.868131
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22250
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW22250
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། འཇིགས་མེད་འཕྲིན་ལས་རྒྱ་མཚོ།
  author: བླ་ཁོ་འཇིགས་མེད་འཕྲིན་ལས་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.5292167809067388
  ocr_word_median_confidence_index: 0.47999998927116394
quality: null
bases:
  I5286:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5286
      total_pages: 856
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I5286.txt
    statistics:
      ocr_word_median_confidence_index: 0.49000000953674316
      ocr_word_mean_confidence_index: 0.5297516156038355
    legacy_id: v006
  I5281:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5281
      total_pages: 864
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5281.txt
    statistics:
      ocr_word_median_confidence_index: 0.4300000071525574
      ocr_word_mean_confidence_index: 0.5030275469981615
    legacy_id: v001
  I5283:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5283
      total_pages: 868
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I5283.txt
    statistics:
      ocr_word_median_confidence_index: 0.49000000953674316
      ocr_word_mean_confidence_index: 0.5333270184109722
    legacy_id: v003
  I5285:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5285
      total_pages: 816
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I5285.txt
    statistics:
      ocr_word_median_confidence_index: 0.5
      ocr_word_mean_confidence_index: 0.5403310047252834
    legacy_id: v005
  I5282:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5282
      total_pages: 830
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I5282.txt
    statistics:
      ocr_word_median_confidence_index: 0.4399999976158142
      ocr_word_mean_confidence_index: 0.5196234114238112
    legacy_id: v002
  I5284:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5284
      total_pages: 828
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I5284.txt
    statistics:
      ocr_word_median_confidence_index: 0.5400000214576721
      ocr_word_mean_confidence_index: 0.5499423554399547
    legacy_id: v004
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
